# Generated by Django 4.2.4 on 2023-08-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bynryuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
