# Generated by Django 4.2.4 on 2023-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequests',
            name='current_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Open'), (1, 'Assigned'), (2, 'In Progress'), (3, 'Customer Response Pending'), (4, 'Scheduled'), (5, 'Completed'), (6, 'Escalated'), (7, 'Closed')], default=0, null=True),
        ),
    ]
