# Generated by Django 4.2.4 on 2023-08-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0002_alter_servicerequests_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bynryuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
