# Generated by Django 4.2.4 on 2023-08-13 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0002_alter_bynryuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bynryuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'manager'), (2, 'Customer')], null=True),
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Installation'), (1, 'Delivery'), (2, 'Safety Inspection'), (3, 'Maintenance'), (4, 'Repairs'), (5, 'Billing Assistance')], null=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, max_length=10)),
                ('description', models.TextField()),
                ('current_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Installation'), (1, 'Delivery'), (2, 'Safety Inspection'), (3, 'Maintenance'), (4, 'Repairs'), (5, 'Billing Assistance')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(to='consumer_services.fileupload')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
