# Generated by Django 4.2.4 on 2023-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_services', '0003_fileupload_alter_bynryuser_role_servicerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequests',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0),
        ),
    ]
